make-server: main.cpp server.cpp client.cpp playerClient.cpp game.cpp rondo.cpp player.cpp playerState.cpp playerStateMachine.cpp playerStates.cpp ball.cpp utility.cpp vector3d.cpp basePiece.cpp movePiece.cpp steering.cpp common/2d/vector2d.cpp 
	g++ -std=c++11 -pthread -o server main.cpp server.cpp client.cpp playerClient.cpp game.cpp rondo.cpp player.cpp playerState.cpp playerStateMachine.cpp playerStates.cpp ball.cpp utility.cpp vector3d.cpp basePiece.cpp movePiece.cpp steering.cpp common/2d/vector2d.cpp -I. 
clean :
	rm server

