make-server: main.cpp server.cpp client.cpp game.cpp rondo.cpp player.cpp utility.cpp vector3d.cpp Common/2D/Vector2D.cpp
	g++ -std=c++11 -pthread -o server main.cpp server.cpp client.cpp game.cpp rondo.cpp player.cpp utility.cpp vector3d.cpp Common/2D/Vector2D.cpp -I. 
clean :
	rm server

